name: Build and deploy to Divio

on: [push]

jobs:
  docker:
    name: Build and push Docker image
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          file: Dockerfile.base
          push: true
          tags: ghcr.io/garetjax/bmcc:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
  divio:
    if: github.ref == 'refs/heads/main'
    name: Deploy to Divio
    needs: docker
    runs-on: ubuntu-latest
    environment:
      name: live
      url: https://bmcc.stoppani.name
    permissions:
      contents: read
    steps:
      -
        name: Install Divio CLI
        run: |
          pip install divio-cli
          hash
      -
        name: Login to Divio
        run: divio login $DEPLOY_TOKEN
        env:
          DEPLOY_TOKEN: ${{ secrets.DIVIO_DEPLOY_TOKEN }}
      -
        name: Deploy to Divio
        run: divio app deploy --remote-id=$APP_ID live
        env:
          APP_ID: ${{ vars.DIVIO_APP_UUID }}
